## EDA & Descriptive Statistics

In [68]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

#Data Loading(Raw+Clean)
raw = pd.read_csv('Crime_Dataset_Coursework1-1.csv')
clean = pd.read_csv('crime_clean.csv')
raw.head(), clean.head()

(   Incident ID Offence Code  CR Number    Dispatch Date / Time NIBRS Code  \
 0    201202980         3550  180042096  08/23/2018 09:52:08 PM        35B
 1    201181293         3522  180015424  03/30/2018 01:00:55 AM        35A
 2    201181293         3562  180015424  03/30/2018 01:00:55 AM        35A
 3    201193163         3520  180029476  06/14/2018 10:26:45 PM        35A
 4    201204355         2204  180043926  09/03/2018 12:06:54 PM        220

    Victims             Crime Name1                     Crime Name2  \
 0        1   Crime Against Society       Drug Equipment Violations
 1        1   Crime Against Society        Drug/Narcotic Violations
 2        1   Crime Against Society        Drug/Narcotic Violations
 3        1   Crime Against Society        Drug/Narcotic Violations
 4        1  Crime Against Property  Burglary/Breaking and Entering

                               Crime Name3 Police District Name  ...  \
 0        DRUGS - NARCOTIC EQUIP - POSSESS           GERMANTOWN  ...
 1   DRUGS - OPIUM OR DERIVATIVE - POSSESS             BETHESDA  ...
 2             DRUGS - MARIJUANA - POSSESS             BETHESDA  ...
 3      DRUGS - OPIUM OR DERIVATIVE - SELL   MONTGOMERY VILLAGE  ...
 4  BURGLARY - NO FORCED ENTRY-RESIDENTIAL             BETHESDA  ...

   Street Prefix     Street Name Street Suffix  Street Type  \
 0           NaN     MIDDLEBROOK           NaN           RD
 1           NaN        WOODMONT           NaN          AVE
 2           NaN        WOODMONT           NaN          AVE
 3           NaN  QUINCE ORCHARD           NaN           RD
 4           NaN        FALSTONE           NaN          AVE

           Start_Date_Time           End_Date_Time   Latitude  Longitude  \
 0  08/23/2018 09:52:00 PM                     NaN  39.177744 -77.265619
 1  03/30/2018 01:01:00 AM                     NaN  38.992693 -77.097063
 2  03/30/2018 01:01:00 AM                     NaN  38.992693 -77.097063
 3  06/14/2018 10:26:00 PM  06/15/2018 03:00:00 AM  39.147954 -77.218189
 4  09/02/2018 11:30:00 PM  09/03/2018 12:30:00 AM  38.966174 -77.096561

   Police District Number             Location
 0                     5D  (39.1777, -77.2656)
 1                     2D  (38.9927, -77.0971)
 2                     2D  (38.9927, -77.0971)
 3                     6D   (39.148, -77.2182)
 4                     2D  (38.9662, -77.0966)

 [5 rows x 30 columns],
    Incident ID Offence Code  CR Number Dispatch Date / Time NIBRS Code  \
 0    201175193         2399  180007927  2018-02-15 12:54:11        23H
 1    201205763         2308  180045732  2018-09-13 12:48:16        23D
 2    201169410         5404  180000017  2018-01-01 02:15:26        90D
 3    201168935         2902  180000064  2018-01-01 11:16:40        290
 4    201174674         5311  180004168  2018-01-25 00:14:22        90C

    Victims             Crime Name1                               Crime Name2  \
 0        1  Crime Against Property                         All Other Larceny
 1        1  Crime Against Property                       Theft From Building
 2        1   Crime Against Society               Driving Under The Influence
 3        1  Crime Against Property  Destruction/Damage/Vandalism Of Property
 4        1   Crime Against Society                        Disorderly Conduct

                           Crime Name3 Police District Name  ...  \
 0          Larceny (Describe Offense)        Silver Spring  ...
 1                 Larceny - From Bldg            Rockville  ...
 2  Driving Under The Influence Liquor           Germantown  ...
 3           Damage Property - Private           Germantown  ...
 4   Public Peace - Disorderly Conduct        Silver Spring  ...

   consistency_score validity_score quality_score quality_tier  \
 0               100             80          94.0    Excellent
 1                70             80          85.0         Good
 2               100             80          94.0    Excellent
 3               100             80          94.0    Excellent
 4               100             80          94.0    Excellent

           Primary Offense  year month weekday hour  District_Norm
 0  Crime Against Property  2018     1  Monday    0  Silver Spring
 1  Crime Against Property  2018     1  Monday   12      Rockville
 2   Crime Against Society  2018     1  Monday    2     Germantown
 3  Crime Against Property  2018     1  Monday    1     Germantown
 4   Crime Against Society  2018     1  Monday    1  Silver Spring

 [5 rows x 39 columns])

In [8]:
#Raw vs Clean data set Comparion
comparison = pd.DataFrame({
    'Metric':['Row Count','Missing Values','Duplicates'],
    'Raw Dataset':[len(raw), raw.isna().sum().sum(), raw.duplicated().sum()],
    'Clean Dataset':[len(clean), clean.isna().sum().sum(), clean.duplicated().sum()]
})
comparison

           Metric  Raw Dataset  Clean Dataset
0       Row Count       306094         203304
1  Missing Values       865131         116890
2      Duplicates            0              0

# Descriptive Statistics Full Section

In [11]:
# load cleaned data set
df = pd.read_csv("crime_clean.csv")
df.head()

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,NIBRS Code,Victims,Crime Name1,Crime Name2,Crime Name3,Police District Name,...,consistency_score,validity_score,quality_score,quality_tier,Primary Offense,year,month,weekday,hour,District_Norm
0,201175193,2399,180007927,2018-02-15 12:54:11,23H,1,Crime Against Property,All Other Larceny,Larceny (Describe Offense),Silver Spring,...,100,80,94.0,Excellent,Crime Against Property,2018,1,Monday,0,Silver Spring
1,201205763,2308,180045732,2018-09-13 12:48:16,23D,1,Crime Against Property,Theft From Building,Larceny - From Bldg,Rockville,...,70,80,85.0,Good,Crime Against Property,2018,1,Monday,12,Rockville
2,201169410,5404,180000017,2018-01-01 02:15:26,90D,1,Crime Against Society,Driving Under The Influence,Driving Under The Influence Liquor,Germantown,...,100,80,94.0,Excellent,Crime Against Society,2018,1,Monday,2,Germantown
3,201168935,2902,180000064,2018-01-01 11:16:40,290,1,Crime Against Property,Destruction/Damage/Vandalism Of Property,Damage Property - Private,Germantown,...,100,80,94.0,Excellent,Crime Against Property,2018,1,Monday,1,Germantown
4,201174674,5311,180004168,2018-01-25 00:14:22,90C,1,Crime Against Society,Disorderly Conduct,Public Peace - Disorderly Conduct,Silver Spring,...,100,80,94.0,Excellent,Crime Against Society,2018,1,Monday,1,Silver Spring

In [12]:
# Standardise column names
df.columns = [c.strip().replace("/", "_").replace(" ", "_") for c in df.columns]
df.columns

Index(['Incident_ID', 'Offence_Code', 'CR_Number', 'Dispatch_Date___Time',
       'NIBRS_Code', 'Victims', 'Crime_Name1', 'Crime_Name2', 'Crime_Name3',
       'Police_District_Name', 'Block_Address', 'City', 'State', 'Zip_Code',
       'Agency', 'Place', 'Sector', 'Beat', 'PRA', 'Address_Number',
       'Street_Name', 'Street_Type', 'Start_Date_Time', 'End_Date_Time',
       'Latitude', 'Longitude', 'Police_District_Number', 'Location',
       'completeness_score', 'consistency_score', 'validity_score',
       'quality_score', 'quality_tier', 'Primary_Offense', 'year', 'month',
       'weekday', 'hour', 'District_Norm'],
      dtype='object')

In [13]:
# Basic Data Summary
df.info()
df.describe(include="all")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 203304 entries, 0 to 203303
Data columns (total 39 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Incident_ID             203304 non-null  int64
 1   Offence_Code            203304 non-null  object
 2   CR_Number               203304 non-null  int64
 3   Dispatch_Date___Time    196966 non-null  object
 4   NIBRS_Code              203304 non-null  object
 5   Victims                 203304 non-null  int64
 6   Crime_Name1             203304 non-null  object
 7   Crime_Name2             203304 non-null  object
 8   Crime_Name3             203304 non-null  object
 9   Police_District_Name    203304 non-null  object
 10  Block_Address           203304 non-null  object
 11  City                    203304 non-null  object
 12  State                   203304 non-null  object
 13  Zip_Code                203304 non-null  object
 14  Agency                  203304 non-null  object
 15  Place                   203304 non-null  object
 16  Sector                  203304 non-null  object
 17  Beat                    203304 non-null  object
 18  PRA                     203304 non-null  object
 19  Address_Number          203304 non-null  float64
 20  Street_Name             203304 non-null  object
 21  Street_Type             203304 non-null  object
 22  Start_Date_Time         203304 non-null  object
 23  End_Date_Time           92752 non-null   object
 24  Latitude                203304 non-null  float64
 25  Longitude               203304 non-null  float64
 26  Police_District_Number  203304 non-null  object
 27  Location                203304 non-null  object
 28  completeness_score      203304 non-null  float64
 29  consistency_score       203304 non-null  int64
 30  validity_score          203304 non-null  int64
 31  quality_score           203304 non-null  float64
 32  quality_tier            203304 non-null  object
 33  Primary_Offense         203304 non-null  object
 34  year                    203304 non-null  int64
 35  month                   203304 non-null  int64
 36  weekday                 203304 non-null  object
 37  hour                    203304 non-null  int64
 38  District_Norm           203304 non-null  object
dtypes: float64(5), int64(8), object(26)
memory usage: 60.5+ MB

,Incident_ID,Offence_Code,CR_Number,Dispatch_Date___Time,NIBRS_Code,Victims,Crime_Name1,Crime_Name2,Crime_Name3,Police_District_Name,...,consistency_score,validity_score,quality_score,quality_tier,Primary_Offense,year,month,weekday,hour,District_Norm
count,2.033040e+05,203304.0,2.033040e+05,196966,203304,203304.000000,203304,203304,203304,203304,...,203304.000000,203304.0,203304.000000,203304,203304,203304.000000,203304.000000,203304,203304.000000,203304
unique,NaN,572.0,NaN,196235,58,NaN,6,60,324,10,...,NaN,NaN,NaN,3,6,NaN,NaN,7,NaN,10
top,NaN,2305.0,NaN,2019-12-02 16:39:39,90Z,NaN,Crime Against Property,All Other Offenses,Larceny - From Auto,Silver Spring,...,NaN,NaN,NaN,Excellent,Crime Against Property,NaN,NaN,Friday,NaN,Silver Spring
freq,NaN,15105.0,NaN,48,54078,NaN,95909,52030,17688,41786,...,NaN,NaN,NaN,192495,95909,NaN,NaN,31616,NaN,41786
mean,2.012781e+08,NaN,1.974387e+08,NaN,NaN,1.022415,NaN,NaN,NaN,NaN,...,99.022670,80.0,93.671189,NaN,NaN,2019.724137,6.231028,NaN,13.141955,NaN
std,6.295190e+04,NaN,1.376745e+07,NaN,NaN,0.183087,NaN,NaN,NaN,NaN,...,4.647971,0.0,1.489177,NaN,NaN,1.351662,3.397584,NaN,6.757288,NaN
min,2.011689e+08,NaN,1.202759e+07,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,50.000000,80.0,69.000000,NaN,NaN,2018.000000,1.000000,NaN,0.000000,NaN
25%,2.012234e+08,NaN,1.900026e+08,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,100.000000,80.0,94.000000,NaN,NaN,2019.000000,3.000000,NaN,9.000000,NaN
50%,2.012783e+08,NaN,2.000078e+08,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,100.000000,80.0,94.000000,NaN,NaN,2020.000000,6.000000,NaN,14.000000,NaN
75%,2.013323e+08,NaN,2.100198e+08,NaN,NaN,1.000000,NaN,NaN,NaN,NaN,...,100.000000,80.0,94.000000,NaN,NaN,2021.000000,9.000000,NaN,19.000000,NaN
max,2.013872e+08,NaN,2.204211e+08,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,...,100.000000,80.0,94.000000,NaN,NaN,2022.000000,12.000000,NaN,23.000000,NaN

# Numerical Descriptive Statistics

In [28]:
# Central Tendacy (Mean, Median, Mode)
numeric_cols = df.select_dtypes(include=[np.number]).columns.tolist()
print("Numeric columns:", numeric_cols)

central_tendency = {}

for col in numeric_cols:
    mode_val = df[col].mode()
    central_tendency[col] = {
        "mean": df[col].mean(),
        "median": df[col].median(),
        "mode": mode_val.iloc[0] if not
        mode_val.empty else None
    }
pd.DataFrame(central_tendency).T

Numeric columns: ['Incident_ID', 'CR_Number', 'Victims', 'Address_Number', 'Latitude', 'Longitude', 'completeness_score', 'consistency_score', 'validity_score', 'quality_score', 'year', 'month', 'hour']

                            mean        median         mode
Incident_ID         2.012781e+08  2.012783e+08  201168913.0
CR_Number           1.974387e+08  2.000078e+08  180020498.0
Victims             1.022415e+00  1.000000e+00          1.0
Address_Number      8.359008e+03  8.100000e+03       8100.0
Latitude            3.784958e+01  3.907234e+01          0.0
Longitude          -7.468447e+01 -7.710076e+01          0.0
completeness_score  9.991097e+01  1.000000e+02        100.0
consistency_score   9.902267e+01  1.000000e+02        100.0
validity_score      8.000000e+01  8.000000e+01         80.0
quality_score       9.367119e+01  9.400000e+01         94.0
year                2.019724e+03  2.020000e+03       2018.0
month               6.231028e+00  6.000000e+00          5.0
hour                1.314195e+01  1.400000e+01          0.0

In [32]:
# Dispersion (Std, Variance, Range, IQR)

dispersion = {}

for col in numeric_cols:
    dispersion[col] = {
        "std": df[col].std(),
        "variance": df[col].var(),
        "min": df[col].min(),
        "max": df[col].max(),
        "range": df[col].max() - df[col].min(),
        "IQR": df[col].quantile(0.75) - df[col].quantile(0.25)
        
    }
    pd.DataFrame(dispersion).T

# Categorical Descriptive Statistics
we detect column names automatically based on common patterns

In [33]:
# Identify Key categorical columns

#Crime type
crime_col = [c for c in df.columns if "crime" in c.lower()][0]
# District
district_col = [c for c in df.columns if "district" in c.lower()][0]
#city
city_col = [c for c in df.columns if "city" in c.lower()][0]

crime_col, district_col, city_col

('Crime_Name1', 'Police_District_Name', 'City')

In [35]:
# Crime Frequency table
crime_freq = pd.DataFrame({
    "count": df[crime_col].value_counts(),
    "percent": df[crime_col].value_counts(normalize=True) * 100
})
crime_freq.head(10)

                        count    percent
Crime_Name1
Crime Against Property  95909  47.175166
Other                   46469  22.856904
Crime Against Society   38280  18.828946
Crime Against Person    19927   9.801578
Not A Crime              2483   1.221324
Unknown                   236   0.116082

In [37]:
# Police District frequency
district_freq = pd.DataFrame({
    "count": df[district_col].value_counts(),
    "percent": df[district_col].value_counts(normalize=True) * 100
})
district_freq

                      count    percent
Police_District_Name
Silver Spring         41786  20.553457
Wheaton               37266  18.330185
Montgomery Village    34846  17.139850
Bethesda              29562  14.540786
Rockville             27850  13.698698
Germantown            26301  12.936784
City Of Takoma Park    4187   2.059477
Takoma Park            1197   0.588773
Other                   224   0.110180
Unknown                  85   0.041809

In [40]:
# City Distribution
city_freq = pd.DataFrame({
    "count": df[city_col].value_counts(),
    "percent": df[city_col].value_counts(normalize=True) * 100
})
city_freq

                 count    percent
City
Silver Spring    68480  33.683548
Gaithersburg     29833  14.674084
Rockville        28312  13.925943
Germantown       20002   9.838469
Bethesda         14525   7.144473
...                ...        ...
North Potomac        1   0.000492
Betheda              1   0.000492
Tacoma Park          1   0.000492
Capitol Heights      1   0.000492
West Friendship      1   0.000492

[65 rows x 2 columns]

## Proportions

In [42]:
#Proportion of Crime types
crime_proportions = df[crime_col].value_counts(normalize=True)
crime_proportions

Crime_Name1
Crime Against Property    0.471752
Other                     0.228569
Crime Against Society     0.188289
Crime Against Person      0.098016
Not A Crime               0.012213
Unknown                   0.001161
Name: proportion, dtype: float64

In [43]:
#Proportion of Districts
district_proportions = df[district_col].value_counts(normalize=True)
district_proportions

Police_District_Name
Silver Spring          0.205535
Wheaton                0.183302
Montgomery Village     0.171398
Bethesda               0.145408
Rockville              0.136987
Germantown             0.129368
City Of Takoma Park    0.020595
Takoma Park            0.005888
Other                  0.001102
Unknown                0.000418
Name: proportion, dtype: float64

In [44]:
#Proportion Of City
city_proportions = df[city_col].value_counts(normalize=True)
city_proportions

City
Silver Spring      0.336835
Gaithersburg       0.146741
Rockville          0.139259
Germantown         0.098385
Bethesda           0.071445
                     ...
North Potomac      0.000005
Betheda            0.000005
Tacoma Park        0.000005
Capitol Heights    0.000005
West Friendship    0.000005
Name: proportion, Length: 65, dtype: float64

## Numerical Summaries - Latitude/Longitude/Time Fields

In [45]:
#Identify Lat/Long Columns
lat_col = [c for c in df.columns if "lat" in c.lower()][0]
lon_col = [c for c in df.columns if "lon" in c.lower()][0]

lat_col, lon_col

('Latitude', 'Longitude')

In [47]:
#Summary of Latitude and Longitude
df[[lat_col, lon_col]].describe()

            Latitude      Longitude
count  203304.000000  203304.000000
mean       37.849581     -74.684468
std         6.830576      13.475846
min         0.000000     -77.516753
25%        39.017900     -77.197160
50%        39.072340     -77.100760
75%        39.141812     -77.028700
max        90.000000       0.000000

In [48]:
#Parse Time Field
time_cols = [c for c in df.columns if "time" in c.lower() or "date" in c.lower()]
time_cols

['Dispatch_Date___Time', 'Start_Date_Time', 'End_Date_Time']

In [55]:
#Assuming first datetime clumn

dt_col = time_cols[0]

df[dt_col] = pd.to_datetime(df[dt_col], errors='coerce')

df['Year'] = df[dt_col].dt.year
df['Month'] = df[dt_col].dt.month
df['Day'] = df[dt_col].dt.day
df['Hour'] = df[dt_col].dt.hour

df[['Year', 'Month', 'Day', 'Hour']].describe()

                Year          Month            Day           Hour
count  196966.000000  196966.000000  196966.000000  196966.000000
mean     2019.758425       6.169232      15.676782      13.482956
std         1.364984       3.376138       8.802325       5.862958
min      2017.000000       1.000000       1.000000       0.000000
25%      2019.000000       3.000000       8.000000      10.000000
50%      2020.000000       6.000000      16.000000      14.000000
75%      2021.000000       9.000000      23.000000      18.000000
max      2022.000000      12.000000      31.000000      23.000000

In [56]:
#Full numerical summary using describe()
df.describe().T

,count,mean,min,25%,50%,75%,max,std
Incident_ID,203304.0,201278058.216002,201168913.0,201223444.75,201278253.5,201332317.25,201387238.0,62951.899911
CR_Number,203304.0,197438662.003758,12027588.0,190002585.75,200007783.5,210019812.25,220421124.0,13767450.520944
Dispatch_Date___Time,196966,2020-03-24 23:35:28.787679488,2017-06-24 04:06:13,2019-01-10 17:32:22.249999872,2020-02-29 07:57:09,2021-06-03 09:56:21.750000128,2022-08-07 18:15:25,NaN
Victims,203304.0,1.022415,1.0,1.0,1.0,1.0,12.0,0.183087
Address_Number,203304.0,8359.007806,1.0,2100.0,8100.0,12000.0,2090600.0,15121.981478
Latitude,203304.0,37.849581,0.0,39.0179,39.07234,39.141812,90.0,6.830576
Longitude,203304.0,-74.684468,-77.516753,-77.19716,-77.10076,-77.0287,0.0,13.475846
completeness_score,203304.0,99.910971,75.0,100.0,100.0,100.0,100.0,1.218447
consistency_score,203304.0,99.02267,50.0,100.0,100.0,100.0,100.0,4.647971
validity_score,203304.0,80.0,80.0,80.0,80.0,80.0,80.0,0.0
quality_score,203304.0,93.671189,69.0,94.0,94.0,94.0,94.0,1.489177
year,203304.0,2019.724137,2018.0,2019.0,2020.0,2021.0,2022.0,1.351662
month,203304.0,6.231028,1.0,3.0,6.0,9.0,12.0,3.397584
hour,203304.0,13.141955,0.0,9.0,14.0,19.0,23.0,6.757288
Year,196966.0,2019.758425,2017.0,2019.0,2020.0,2021.0,2022.0,1.364984
Month,196966.0,6.169232,1.0,3.0,6.0,9.0,12.0,3.376138
Day,196966.0,15.676782,1.0,8.0,16.0,23.0,31.0,8.802325
Hour,196966.0,13.482956,0.0,10.0,14.0,18.0,23.0,5.862958

## Group by Analysis

In [58]:
#Crime count by district
df.groupby(district_col)[crime_col].count()

Police_District_Name
Bethesda               29562
City Of Takoma Park     4187
Germantown             26301
Montgomery Village     34846
Other                    224
Rockville              27850
Silver Spring          41786
Takoma Park             1197
Unknown                   85
Wheaton                37266
Name: Crime_Name1, dtype: int64

In [60]:
#Crime count by ciy
df.groupby(city_col)[crime_col].count()

City
0                     1
Adelphi               1
Alexandria            1
Ashton              255
Barnesville          29
                   ...
Washington           18
Washington Grove      8
West Friendship       1
Wheaton               4
Woodbine              4
Name: Crime_Name1, Length: 65, dtype: int64

In [62]:
#Crime count by year
df.groupby("year")[crime_col].count()

year
2018    49705
2019    47229
2020    40965
2021    40255
2022    25150
Name: Crime_Name1, dtype: int64

## Value_Counts() Summaries

In [63]:
#Top Crime Types
df[crime_col].value_counts().head(20)

Crime_Name1
Crime Against Property    95909
Other                     46469
Crime Against Society     38280
Crime Against Person      19927
Not A Crime                2483
Unknown                     236
Name: count, dtype: int64

In [66]:
#Top Cities
df[city_col].value_counts().head(20)

City
Silver Spring         68480
Gaithersburg          29833
Rockville             28312
Germantown            20002
Bethesda              14525
Montgomery Village     6040
Takoma Park            5687
Potomac                4448
Chevy Chase            4409
Derwood                3878
Kensington             3297
Olney                  3048
Burtonsville           2526
Clarksburg             2203
Damascus               1732
Boyds                  1398
Unknown                 856
Brookeville             651
Poolesville             630
Sandy Spring            292
Name: count, dtype: int64

In [67]:
#Top Districts
df[district_col].value_counts().head()

Police_District_Name
Silver Spring         41786
Wheaton               37266
Montgomery Village    34846
Bethesda              29562
Rockville             27850
Name: count, dtype: int64